# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool: 
  name: 'Default'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |

    echo -e $APPINSTALL | sudo python3 -m pip install --upgrade pip
    echo -e $APPINSTALL | sudo pip3 install virtualenv
    echo -e $APPINSTALL | sudo pip3 install --upgrade setuptools
    echo -e $APPINSTALL | sudo python3 -m venv pytestenv && cd pytestenv && source pytestenv/bin/activate
    echo -e $APPINSTALL | sudo pip install -r requirements.txt
    echo -e $APPINSTALL | sudo pip install pytest pytest-azurepipelines
    echo -e $APPINSTALL | sudo pytest
